name: brian2-paper-examples
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cython=0.27*
  - nose=1.3*
  - ipywidgets=7.4*
  - widgetsnbextension=3.4*
  - plotly=3.6*
  - sympy=1.3*
  - scipy=1.2*
  - matplotlib=2.1*
  - ipympl=0.2*
  - pip:
     - "git+https://github.com/brian-team/brian2.git"
